

app:
  name: Ecommerce-basic
  port: ":4000"
  encryption:
    salt: 10
    jwt_secret: iniAdalahSecretToken

db:
  host: ${PGHOST}
  port: ${PGPORT}
  name: ${PGDATABASE}
  user: ${PGUSER}
  password: ${PGPASSWORD}
  connection_pool:
    max_idle_connection: 10
    max_open_connection: 30
    max_lifetime_connection: 60 # second
    max_idletime_connection: 60 # second